apiVersion: v1
kind: Namespace
metadata:
  name: openevals-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openevals-backend-app
  namespace: openevals-backend
spec:
  selector:
    matchLabels:
      app: openevals-backend-app
  replicas: $DESIRED_REPLICAS
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: openevals-backend-app
    spec:
      nodeSelector:
        group-type: $AWS_GROUP_TYPE
      containers:
        - name: openevals-backend-app
          image: 248189933412.dkr.ecr.$AWS_REGION_NAME.amazonaws.com/openevals-deployment:backend-$ENVIRONMENT-latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: openevals-backend-service
  namespace: openevals-backend
  annotations:
    app: openevals-backend-app
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: $SSL_ARN
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-redirect: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP
  selector:
    app: openevals-backend-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openevals-backend-hpa
  namespace: openevals-backend
  annotations:
    app: openevals-backend-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openevals-backend-app
  minReplicas: $MIN_REPLICAS
  maxReplicas: $MAX_REPLICAS
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
