apiVersion: v1
kind: Namespace
metadata:
  name: openevals-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openevals-client-app
  namespace: openevals-client
spec:
  selector:
    matchLabels:
      app: openevals-client-app
  replicas: $DESIRED_REPLICAS
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: openevals-client-app
    spec:
      nodeSelector:
        group-type: $AWS_GROUP_TYPE
      containers:
        - name: openevals-client-app
          image: 160885253688.dkr.ecr.$AWS_REGION_NAME.amazonaws.com/openevals-client:openevals-client-$ENVIRONMENT-latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 256Mi 
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: openevals-client-service
  namespace: openevals-client
  annotations:
    app: openevals-client-app
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: $SSL_ARN
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-ssl-redirect: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: 'ELBSecurityPolicy-TLS13-1-2-2021-06'
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: 'HTTP2Preferred'
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP
  selector:
    app: openevals-client-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openevals-client-hpa
  namespace: openevals-client
  annotations:
    app: openevals-client-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openevals-client-app
  minReplicas: $MIN_REPLICAS
  maxReplicas: $MAX_REPLICAS
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
