name: Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "20"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies and run tsc
        run: |
          cd $GITHUB_WORKSPACE/client
          pnpm install
          pnpm run tsc
