name: Deploy backend service
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.eks_deploy/backend.yml'
      - '.github/workflows/deploy-backend.yml'

env:
  ECR_REPO_NAME: 'openevals-backend'
  AWS_REGION_NAME: 'us-west-1'
  CLUSTER_NAME: 'openevals-prod'
  ENVIRONMENT: 'prod'
  DESIRED_REPLICAS: 6
  MIN_REPLICAS: 6
  MAX_REPLICAS: 15
  SSL_ARN: ${{ secrets.BACKEND_SSL_ARN }}
  AWS_GROUP_TYPE: 'general-processing'

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate env file
        run: |
          REST_OF_ENV=$(cat << EOF
          DEBUG=0
          ENVIRONMENT=production
          POSTGRESQL_HOST=${{ secrets.POSTGRESQL_HOST }}
          POSTGRESQL_USERNAME=${{ secrets.POSTGRESQL_USERNAME }}
          POSTGRESQL_PASSWORD=${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRESQL_DATABASE=openevals
          GITHUB_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET=${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          WEB_URL=https://www.openevals.org
          PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}
          EOF
          )
          echo "$REST_OF_ENV" >> ./backend/.env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: openevals-backend-${{ env.ENVIRONMENT }}-latest
        run: |
          # Build a docker container and push it to ECR
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Install and configure kubectl
        run: |
          VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
          curl https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl \
              --progress-bar \
              --location \
              --remote-name
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION_NAME }}
    
      - name: Deploy
        run: |
          cat .eks_deploy/backend.yml | envsubst > .eks_deploy/backend-updated.yml
          kubectl apply -f .eks_deploy/backend-updated.yml --force --grace-period=5
          kubectl -n openevals-backend rollout restart deploy
          kubectl -n openevals-backend rollout status deploy

      - name: Print nice message on completion of CI Pipeline
        run: echo "CI Pipeline part finished successfully"
